---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Get service facts
      service_facts:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      vars:
        ansible_become: true
      when: inventory_hostname == 'web'

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true
      when: inventory_hostname == 'web'

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      vars:
        ansible_become: true
      when: inventory_hostname == 'database'

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: true
      when: inventory_hostname == 'database'
    - name: Check service docker status
      debug:
        var: ansible_facts.services['docker'].state
    - name: Check service mysql status
      debug:
        var: ansible_facts.services['mysql'].state
      when: inventory_hostname == 'database'
    - name: Check service apache status
      debug:
        var: ansible_facts.services['apache2'].state
      when: inventory_hostname == 'web'
